### Numpy

In [79]:
import numpy as np

### 创建numpy数组

#### 使用numpy.array()函数
* 通过List创建numpy数组

In [80]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


* 通过tuple创建numpy数组

In [42]:
b = np.array([(1, 2, 3), (4, 5, 6)])
print(b)

[[1 2 3]
 [4 5 6]]


#### 使用arange()函数创建数组

In [43]:
c = np.arange(20)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [88]:
d = np.arange(10,20)
print(d)

[10 11 12 13 14 15 16 17 18 19]


In [89]:
e = np.arange(10,20, 3)
print(e)

[10 13 16 19]


#### 使用reshape()函数创建数组

In [91]:
f = np.arange(20)
g = f.reshape(4, 5)
print(g)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [92]:
h = g.reshape(5, 4)
print(h)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [93]:
i = h.reshape(2, 2, 5)
print(i)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]


#### 使用zeros()函数创建数组

In [94]:
j = np.zeros((3, 4))
print(j)
print(j.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
float64


In [95]:
k = np.zeros((3, 4), dtype=np.int16)
print(k)
print(k.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int16


In [87]:
print(type(d))

<class 'numpy.ndarray'>


In [46]:
print(d.ndim)
print(d.shape)
print(d.shape[0])
print(d.shape[1])
print(d.size)
print(d.dtype)
print(d.itemsize)
print(d.dtype.itemsize)
print(d.data)

2
(4, 5)
4
5
20
int32
4
4


In [47]:
e = np.arange(60)
print(e)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59]


In [48]:
f = e.reshape(3, 4, 5)
print(f)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]


In [49]:
print(f.ndim)
print(f.shape)
print(f.shape[0])
print(f.shape[1])
print(f.shape[2])
print(f.size)
print(f.dtype)
print(f.itemsize)
print(f.dtype.itemsize)
print(f.data)

3
(3, 4, 5)
3
4
5
60
int32
4
4


In [50]:
g = np.array(((1, 2, 3), (4, 5, 6)))
print(g)

[[1 2 3]
 [4 5 6]]


In [51]:
h = np.arange(8, dtype=complex)
i = h.reshape(2, 4)
print(i)

[[0.+0.j 1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j 7.+0.j]]


In [68]:
j = np.zeros((3, 4))
print(j)
print(j.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
float64


In [69]:
k = np.zeros((3, 4), dtype=np.int16)
print(k)
print(k.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int16


In [72]:
l = np.ones((2, 3, 4), dtype=np.int32)
print(l)
print(l.dtype)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
int32


In [73]:
j = np.empty((2,3))
print(j)
print(j.dtype)

[[7.e-322 0.e+000 0.e+000]
 [0.e+000 0.e+000 0.e+000]]
float64


In [78]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])