### Numpy快速入门简明教程

本教程是Numpy的入门教程，基于官方《[Quickstart tutorial](https://docs.scipy.org/doc/numpy/user/quickstart.html)》

numpy不是Python默认内置模块，所以在使用numpy之前，我们需要导入numpy模块：

In [2]:
import numpy as np

### 创建numpy数组

#### 使用numpy.array()函数
* 通过List创建numpy数组

  传入Python标准的list

In [3]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


* 通过tuple创建numpy数组

  传入tuple

In [5]:
b = np.array(((1, 2, 3), (4, 5, 6)))
print(b)

[[1 2 3]
 [4 5 6]]


#### 使用arange()函数创建数组

arange()函数创建序列数组

In [8]:
c = np.arange(20)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [9]:
d = np.arange(10,20)
print(d)

[10 11 12 13 14 15 16 17 18 19]


In [10]:
e = np.arange(10,20, 3)
print(e)

[10 13 16 19]


#### 使用linspace()函数创建数组

linspace()同样可以像arange()函数那样创建序列数组

In [24]:
e = np.linspace(0, 2, 9)
print(e)
print(e.dtype)

from numpy import pi
e = np.linspace(0, 2*pi, 10)
e = np.sin(e)
print(e)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
float64
[ 0.00000000e+00  6.42787610e-01  9.84807753e-01  8.66025404e-01
  3.42020143e-01 -3.42020143e-01 -8.66025404e-01 -9.84807753e-01
 -6.42787610e-01 -2.44929360e-16]


#### 使用reshape()函数创建数组

reshape()函数可以把已有的数组变换维度，进行重组。

> 注意，必须保证数组的element个数不变

In [91]:
f = np.arange(20)
g = f.reshape(4, 5)
print(g)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [92]:
h = g.reshape(5, 4)
print(h)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [93]:
i = h.reshape(2, 2, 5)
print(i)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]


#### 使用zeros()函数创建数组

zeros()函数可以创建一个值全为0的数组

In [12]:
j = np.zeros((3, 4))
print(j)
print(j.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
float64


In [13]:
k = np.zeros((3, 4), dtype=np.int16)
print(k)
print(k.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int16


#### 使用ones()函数创建数组

ones()函数可以创建一个值全为1的数组

In [14]:
l = np.ones((2, 3, 4), dtype=np.int32)
print(l)
print(l.dtype)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
int32


#### 使用empty() 函数创建数组

empty()函数可以创建一个初始值为随机数的数组

In [17]:
m = np.empty((3, 2 , 1))
print(m)
print(m.dtype)

[[[9.e-323]
  [0.e+000]]

 [[0.e+000]
  [0.e+000]]

 [[0.e+000]
  [0.e+000]]]
float64


### numpy数组属性

numpy所有数组的类型是`ndarray`，可以通过Python的type()函数查看：

In [26]:
d = np.array([[1, 2, 3], [4, 5, 6]])
print(type(d))

<class 'numpy.ndarray'>


numpy所有数组具有如下属性：

`ndim`, `shape`, `size`, `dtype`, `itemsize`, `data`

In [31]:
e = np.arange(60)
f = e.reshape(3, 4, 5)
print(f)
print(f.ndim)
print(f.shape)
print(f.shape[0])
print(f.shape[1])
print(f.shape[2])
print(f.size)
print(f.dtype)
print(f.itemsize)
print(f.dtype.itemsize)
print(f.data)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]
3
(3, 4, 5)
3
4
5
60
int32
4
4


创建数组时，通过传入dtype参数可以指定数组中数据的类型：

In [34]:
h = np.arange(8, dtype=complex)
i = h.reshape(2, 4)
print(i)
print(i.dtype)

[[0.+0.j 1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j 7.+0.j]]
complex128


In [35]:
k = np.zeros((3, 4), dtype=np.int16)
print(k)
print(k.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int16


In [37]:
l = np.ones((2, 3, 4), dtype=np.int32)
print(l)
print(l.dtype)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
int32


### Numpy基本操作

在numpy中，算术运算符如`+`, `-`, `*`, `/`等会作用在数组的每个element上。

In [45]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
print(a)
print(b)

[20 30 40 50]
[0 1 2 3]


In [46]:
c = a - b
print(c)

[20 29 38 47]


In [47]:
d = b ** 2
print(d)

[0 1 4 9]
